const notesToKeys = newMap();
  notesToKeys.set("c", "a");
  notesToKeys.set("d", "s");
  notesToKeys.set("e", "d");
  notesToKeys.set("f", "f");
  notesToKeys.set("g", "j");
  notesToKeys.set("a", "k");
  notesToKeys.set("b", "l");
  notesToKeys.set("c1", ";");
  notesToKeys.set("g0", "w");
  notesToKeys.set("a0", "e");
  notesToKeys.set("b0", "r");
  notesToKeys.set("d1", "i");
  notesToKeys.set("e1", "o");
  notesToKeys.set("f1", "p");

const keyCodes = newMap();
  keyCodes.set("a", 65);
  keyCodes.set("s", 83);
  keyCodes.set("d", 68);
  keyCodes.set("f", 70);
  keyCodes.set("j", 74);
  keyCodes.set("k", 75);
  keyCodes.set("l", 76);
  keyCodes.set(";", 186);
  keyCodes.set("w", 87);
  keyCodes.set("e", 69);
  keyCodes.set("r", 82);
  keyCodes.set("i", 73);
  keyCodes.set("o", 79);
  keyCodes.set("p", 80);

const sounds = newMap();
  sounds.set(65, );
  sounds.set(83, );
  sounds.set(68, );
  sounds.set(70, );
  sounds.set(74, );
  sounds.set(75, );
  sounds.set(76, );
  sounds.set(186, );
  sounds.set(87, );
  sounds.set(69, );
  sounds.set(82, );
  sounds.set(73, );
  sounds.set(79, );
  sounds.set(80, );
